# 🧼 Cleaning Dirty Data (Missing Values & Type Fixes)

## 🔹 LEARNING GOALS:
- Detect and count missing values (`NaN`)
- Fill or drop missing data
- Convert column data types safely
- Understand the difference between `NaN`, `None`, `""`, and type mismatches

### 🧪 1. Load a Messy Dataset

In [1]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", None],
    "Age": ["25", "thirty", 35, np.nan, "40"],
    "Signup Date": ["2022-01-01", "not a date", "2022/03/01", None, "April 5, 2022"],
    "Score": [95.5, None, 88.0, 92.5, ""]
}

df = pd.DataFrame(data)
df

      Name     Age    Signup Date Score
0    Alice      25     2022-01-01  95.5
1      Bob  thirty     not a date  None
2  Charlie      35     2022/03/01  88.0
3    David     NaN            NaN  92.5
4      NaN      40  April 5, 2022

### 🧯 2. Detecting Missing or Broken Values

In [2]:
df.isnull()

    Name    Age  Signup Date  Score
0  False  False        False  False
1  False  False        False   True
2  False  False        False  False
3  False   True         True  False
4   True  False        False  False

In [3]:
df.isnull().sum()

Name           1
Age            1
Signup Date    1
Score          1
dtype: int64

In [4]:
df[df.isnull().any(axis=1)]

    Name     Age    Signup Date Score
1    Bob  thirty     not a date  None
3  David     NaN            NaN  92.5
4    NaN      40  April 5, 2022

### 🧹 3. Cleaning Strategy Options

In [5]:
df.fillna({
    "Name": "Unknown",
    "Age": -1,
    "Signup Date": "1970-01-01",
    "Score": 0.0
})

      Name     Age    Signup Date Score
0    Alice      25     2022-01-01  95.5
1      Bob  thirty     not a date   0.0
2  Charlie      35     2022/03/01  88.0
3    David      -1     1970-01-01  92.5
4  Unknown      40  April 5, 2022

In [6]:
df.dropna()

      Name Age Signup Date Score
0    Alice  25  2022-01-01  95.5
2  Charlie  35  2022/03/01  88.0

### 🧬 4. Data Type Fixes

In [7]:
df.dtypes

Name              str
Age            object
Signup Date       str
Score          object
dtype: object

In [8]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Score"] = pd.to_numeric(df["Score"], errors="coerce")
df["Signup Date"] = pd.to_datetime(df["Signup Date"], errors="coerce")
df.dtypes

Name                      str
Age                   float64
Signup Date    datetime64[us]
Score                 float64
dtype: object

### 🩹 5. Impute (Fill In) Fixed Missing Values

In [9]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Score"] = df["Score"].fillna(df["Score"].mean())

In [10]:
df["Signup Date"] = df["Signup Date"].fillna(df["Signup Date"].min())

In [11]:
df["Name"] = df["Name"].fillna("Unknown")

### 🤓 6. Cleaned Data Review

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         5 non-null      str
 1   Age          5 non-null      float64
 2   Signup Date  5 non-null      datetime64[us]
 3   Score        5 non-null      float64
dtypes: datetime64[us](1), float64(2), str(1)
memory usage: 292.0 bytes

In [13]:
df.describe(include="all")

         Name        Age          Signup Date     Score
count       5   5.000000                    5   5.00000
unique      5        NaN                  NaN       NaN
top     Alice        NaN                  NaN       NaN
freq        1        NaN                  NaN       NaN
mean      NaN  34.000000  2022-01-01 00:00:00  92.00000
min       NaN  25.000000  2022-01-01 00:00:00  88.00000
25%       NaN  35.000000  2022-01-01 00:00:00  92.00000
50%       NaN  35.000000  2022-01-01 00:00:00  92.00000
75%       NaN  35.000000  2022-01-01 00:00:00  92.50000
max       NaN  40.000000  2022-01-01 00:00:00  95.50000
std       NaN   5.477226                  NaN   2.66927

### 🧪 Try It Yourself

Modify the `data` dictionary at the top of this notebook. Add:
- A new column with some `None` and `""` values
- At least one row with all columns filled incorrectly
Then re-run the notebook and fix it step-by-step.

### 🧠 Mini-Challenge

> 🗂 Load `"data/survey.csv"` and:
- Identify which columns have missing values
- Use `.isnull().sum()` to get a null report
- Use a mix of `.fillna()`, `.dropna()`, and `pd.to_numeric()` or `pd.to_datetime()` to clean it
- Print a summary with `.info()` and `.describe()`

In [14]:
# Completed reference solution: survey cleaning mini-challenge
survey = pd.read_csv("../../data/survey.csv")

null_report = survey.isnull().sum().sort_values(ascending=False)
display(null_report)

clean = survey.copy()
for col in ["age", "gpa", "study_hours_per_week", "satisfaction_1_5", "expected_grad_year", "commute_minutes"]:
    clean[col] = pd.to_numeric(clean[col], errors="coerce")

clean["survey_date"] = pd.to_datetime(clean["survey_date"], errors="coerce")
clean["attendance_rate"] = pd.to_numeric(clean["attendance_rate"].astype("string").str.replace("%", "", regex=False), errors="coerce")
clean = clean.dropna(subset=["student_id"])

for col in clean.select_dtypes(include="number").columns:
    clean[col] = clean[col].fillna(clean[col].median())

clean.info()
display(clean.select_dtypes("number").describe())

attendance_rate         79
commute_minutes         53
comments                52
satisfaction_1_5        46
gpa                     44
study_hours_per_week    42
dorm_resident           33
age                     33
expected_grad_year      33
survey_date             32
clubs_member            25
gender                  23
income_range            21
favorite_language       19
major                   10
student_id               0
dtype: int64

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            120 non-null    str
 1   age                   120 non-null    float64
 2   gender                97 non-null     str
 3   major                 110 non-null    str
 4   gpa                   120 non-null    float64
 5   study_hours_per_week  120 non-null    float64
 6   satisfaction_1_5      120 non-null    float64
 7   survey_date           61 non-null     datetime64[us]
 8   dorm_resident         87 non-null     str
 9   expected_grad_year    120 non-null    float64
 10  income_range          99 non-null     str
 11  commute_minutes       120 non-null    float64
 12  clubs_member          95 non-null     str
 13  attendance_rate       120 non-null    Int64
 14  favorite_language     101 non-null    str
 15  comments              68 non-null     str
dtypes: Int64(1), datetime64[us](1), float64(6), str(8)
memory usage: 15.2 KB

C:\Users\demii\AppData\Local\Temp\ipykernel_13588\2938664340.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  clean["survey_date"] = pd.to_datetime(clean["survey_date"], errors="coerce")

,age,gpa,study_hours_per_week,satisfaction_1_5,expected_grad_year,commute_minutes,attendance_rate
count,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.0
mean,21.158333,3.953917,10.595833,2.941667,2028.016667,4.650000,102.033333
std,1.887579,0.596854,7.632388,0.891565,1.053073,15.138381,8.836454
min,18.000000,2.030000,-3.000000,1.000000,2026.000000,-5.000000,62.0
25%,20.000000,3.750000,7.750000,3.000000,2028.000000,0.000000,105.0
50%,21.000000,3.750000,12.500000,3.000000,2028.000000,0.000000,105.0
75%,22.000000,3.750000,12.500000,3.000000,2028.000000,0.000000,105.0
max,25.000000,5.100000,30.000000,5.000000,2030.000000,75.000000,105.0

### 📝 Summary

| Concept        | Tool/Function                      |
|----------------|------------------------------------|
| Detect nulls   | `df.isnull()`, `df.isnull().sum()` |
| Drop rows      | `df.dropna()`                      |
| Fill values    | `df.fillna()`                      |
| Convert types  | `pd.to_numeric()`, `pd.to_datetime()` |
| Replace values | `df.replace()`                     |