# 🧮 Sorting & Filtering in Pandas

## 🔹 LEARNING GOALS:
- Sort rows using `.sort_values()`
- Filter data using conditional logic
- Chain multiple filters together
- Use `.query()` for readable filtering

### 📥 1. Load the Dataset

In [1]:
import pandas as pd
from pathlib import Path

student_path = Path("../../data/students.csv")
if not student_path.exists():
    pd.DataFrame({
        "first_name": ["Ava", "Ben", "Cora", "Diego"],
        "last_name": ["Nguyen", "Smith", "Patel", "Garcia"],
        "math_score": [95, 82, 100, 74],
        "science_score": [88, 82, 97, 74],
    }).to_csv(student_path, index=False)

df = pd.read_csv(student_path)
df.head()

  first_name last_name  math_score  science_score
0        Ava    Nguyen        95.0           88.0
1        Ben     Smith        82.0           79.0
2       Cora     Patel         NaN           93.0
3      Diego    Garcia        74.0            NaN
4       Ella     Brown        68.0           72.0

### 🔢 2. Sorting Data

In [2]:
# Sort by math_score
df.sort_values(by="math_score")

  first_name last_name  math_score  science_score
4       Ella     Brown        68.0           72.0
3      Diego    Garcia        74.0            NaN
1        Ben     Smith        82.0           79.0
5       Finn     Jones        91.0           96.0
0        Ava    Nguyen        95.0           88.0
2       Cora     Patel         NaN           93.0

In [3]:
# Sort by science_score descending
df.sort_values(by="science_score", ascending=False)

  first_name last_name  math_score  science_score
5       Finn     Jones        91.0           96.0
2       Cora     Patel         NaN           93.0
0        Ava    Nguyen        95.0           88.0
1        Ben     Smith        82.0           79.0
4       Ella     Brown        68.0           72.0
3      Diego    Garcia        74.0            NaN

In [4]:
# Sort by multiple columns
df.sort_values(by=["science_score", "math_score"], ascending=[False, True])

  first_name last_name  math_score  science_score
5       Finn     Jones        91.0           96.0
2       Cora     Patel         NaN           93.0
0        Ava    Nguyen        95.0           88.0
1        Ben     Smith        82.0           79.0
4       Ella     Brown        68.0           72.0
3      Diego    Garcia        74.0            NaN

### 🧪 3. Filtering with Conditions

In [5]:
# Who scored at least 90 in math?
df[df["math_score"] >= 90]

  first_name last_name  math_score  science_score
0        Ava    Nguyen        95.0           88.0
5       Finn     Jones        91.0           96.0

In [6]:
# Who scored less than 70 in either subject?
df[(df["math_score"] < 70) | (df["science_score"] < 70)]

  first_name last_name  math_score  science_score
4       Ella     Brown        68.0           72.0

### 🔗 4. Combining Filters

In [7]:
# Students with B+ or higher in both
df[(df["math_score"] >= 87) & (df["science_score"] >= 87)]

  first_name last_name  math_score  science_score
0        Ava    Nguyen        95.0           88.0
5       Finn     Jones        91.0           96.0

### 🧾 5. Using `.query()` for Readability

In [8]:
# Same query using .query()
df.query("math_score >= 87 and science_score >= 87")

  first_name last_name  math_score  science_score
0        Ava    Nguyen        95.0           88.0
5       Finn     Jones        91.0           96.0

### 🧪 Try It Yourself

- Sort the dataset by first name alphabetically
- Find students with the same math and science score
- Use `.query()` to find students who scored over 95 in *either* subject

In [9]:
# Completed reference solution
display(df.sort_values("first_name"))
display(df[df["math_score"] == df["science_score"]])
display(df.query("math_score > 95 or science_score > 95"))

  first_name last_name  math_score  science_score
0        Ava    Nguyen        95.0           88.0
1        Ben     Smith        82.0           79.0
2       Cora     Patel         NaN           93.0
3      Diego    Garcia        74.0            NaN
4       Ella     Brown        68.0           72.0
5       Finn     Jones        91.0           96.0

Empty DataFrame
Columns: [first_name, last_name, math_score, science_score]
Index: []

  first_name last_name  math_score  science_score
5       Finn     Jones        91.0           96.0

### 🧠 Mini-Challenge

> Load `"data/survey.csv"` and:
- Sort by the most recent signup date
- Filter out anyone who didn't complete the survey (nulls or "N/A")
- Use `.query()` to select rows with a specific condition of your choice

In [10]:
# Completed reference solution: survey sorting challenge
survey = pd.read_csv("../../data/survey.csv")
survey["survey_date"] = pd.to_datetime(survey["survey_date"], errors="coerce")
survey["age"] = pd.to_numeric(survey["age"], errors="coerce")
recent = survey.sort_values("survey_date", ascending=False)
completed = survey.replace("N/A", pd.NA).dropna(thresh=int(survey.shape[1] * 0.75))
specific = completed.query("age == age and age >= 21")
display(recent.head())
display(completed.head())
display(specific.head())

C:\Users\demii\AppData\Local\Temp\ipykernel_24480\4287404117.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  survey["survey_date"] = pd.to_datetime(survey["survey_date"], errors="coerce")

,student_id,age,gender,major,gpa,study_hours_per_week,satisfaction_1_5,survey_date,dorm_resident,expected_grad_year,income_range,commute_minutes,clubs_member,attendance_rate,favorite_language,comments
76,S10076,19.0,Male,CS,NaN,0,five,2025-11-30,Yes,NaN,<$25k,50,1,NaN,NaN,Love the course.
58,S10058,21.0,Prefer not to say,CS,NaN,20,5,2025-11-29,Y,2030,$50k-$75k,1,0,105%,Rust,NaN
20,S10020,20.0,Prefer not to say,CompSci,"4,0",NaN,2,2025-11-28,Yes,2026,NaN,NaN,1,NaN,Python,Too much homework.
26,S10026,21.0,Prefer not to say,NaN,NaN,NaN,NaN,2025-11-26,Yes,twenty28,NaN,NaN,NaN,NaN,Go,NaN
96,S10096,24.0,NaN,Math,NaN,NaN,NaN,2025-11-24,NaN,twenty28,>$100k,NaN,0,NaN,NaN,Lectures are 🔥

,student_id,age,gender,major,gpa,study_hours_per_week,satisfaction_1_5,survey_date,dorm_resident,expected_grad_year,income_range,commute_minutes,clubs_member,attendance_rate,favorite_language,comments
0,S10000,NaN,Male,Computer Science,NaN,NaN,2,NaT,Yes,2027,>$100k,54,TRUE,105%,JavaScript,Love the course.
8,S10008,NaN,Male,History,"4,0",ten,3,2025-10-18,Yes,2026,>$100k,-5,TRUE,NaN,Go,Love the course.
9,S10009,18.0,Female,NaN,3.88,NaN,2,2025-11-08,N,twenty28,>$100k,NaN,1,NaN,JavaScript,Too much homework.
10,S10010,NaN,Non-binary,CS,NaN,ten,4,2025-09-09,Y,2029,>$100k,28,FALSE,74%,Python,NaN
11,S10011,18.0,Non-binary,Data Science,NaN,NaN,4,2025-11-09,No,twenty28,$25k-$50k,0,No,NaN,C++,Love the course.

,student_id,age,gender,major,gpa,study_hours_per_week,satisfaction_1_5,survey_date,dorm_resident,expected_grad_year,income_range,commute_minutes,clubs_member,attendance_rate,favorite_language,comments
12,S10012,24.0,Prefer not to say,CS,3.7,NaN,1,NaT,NaN,2027,$25k-$50k,45 min,0,NaN,SQL,Too much homework.
13,S10013,25.0,Female,Data Science,5.1,-3,2,NaT,Yes,2026,<$25k,NaN,1,NaN,NaN,Need more examples.
23,S10023,22.0,Male,History,"4,0",-3,NaN,2025-09-04,NaN,2028,>$100k,33,FALSE,NaN,SQL,NaN
30,S10030,21.0,Non-binary,Business,"4,0",NaN,3,NaT,No,2028,Prefer not to say,NaN,1,NaN,Go,Need more examples.
32,S10032,25.0,Male,Undeclared,3.75,0,3,2025-10-30,Yes,2026,$75k-$100k,75,FALSE,NaN,SQL,NaN

### 📝 Summary

| Task              | Code Example                                 |
|-------------------|-----------------------------------------------|
| Sort by column     | `df.sort_values(by="col")`                  |
| Filter condition   | `df[df["col"] > value]`                     |
| Combine filters    | `df[(cond1) & (cond2)]`                     |
| Query method       | `df.query("col > value and col2 < value")`  |