
# 🧼 Data Cleaning Lab: Survey Edition

Welcome to the data cleaning battlefield! This notebook contains a messy `survey_dirty.csv` file full of inconsistencies, missing values, and formatting nightmares. Your task is to clean it up using pandas and your data wrangling skills.

---

📁 **File to use**: `survey_dirty.csv`  
📊 **Goal**: Practice common data cleaning tasks on a realistic (but slightly cursed) dataset.


## ✅ Cleaning Tasks

Complete the following tasks step-by-step. Use new cells for each task and document your process.

### 1. Load and inspect the data
- Load the CSV file into a DataFrame
- Display the first few rows and basic info (`df.info()`)

### 2. Clean up string fields
- Strip whitespace from `name`, `email`, and other string columns
- Identify blank strings and convert them to NaN if needed

### 3. Handle missing values
- Identify columns with missing data
- Decide how to handle them: drop, fill, or flag (justify your choices)

### 4. Standardize categorical data
- Convert `gender` values to consistent categories (`Male`, `Female`, `Other`)
- Normalize `exercise_freq` to a standard set of categories

### 5. Fix data types
- Convert `age`, `height_cm`, `weight_kg`, and `satisfaction` to numeric
- Extract numbers from strings (e.g., "175cm" → 175)
- Convert `submitted_at` to datetime

### 6. Validate and clean emails
- Use regex or string methods to filter out invalid email addresses

### 7. Convert consent to Boolean
- Standardize `consent_given` to True/False values

### 8. Check for duplicates
- Identify any duplicated rows or IDs
- Drop or resolve as needed

### 9. Save your cleaned data
- Save the cleaned DataFrame to a new file called `survey_clean.csv`

In [1]:
import pandas as pd
import numpy as np

# The repo includes survey.csv rather than survey_dirty.csv; this file is intentionally messy.
df = pd.read_csv("../../data/survey.csv")
df.head()

,student_id,age,gender,major,gpa,study_hours_per_week,satisfaction_1_5,survey_date,dorm_resident,expected_grad_year,income_range,commute_minutes,clubs_member,attendance_rate,favorite_language,comments
0,S10000,NaN,Male,Computer Science,NaN,NaN,2,2025-13-40,Yes,2027,>$100k,54,TRUE,105%,JavaScript,Love the course.
1,S10001,NaN,Male,CompSci,3.75,-3,NaN,NaN,Yes,NaN,NaN,NaN,1,NaN,Rust,Lectures are 🔥
2,S10002,23,Male,Data Science,NaN,20,5,2025-13-40,NaN,2027,$75k-$100k,NaN,NaN,64%,JavaScript,NaN
3,S10003,NaN,Female,History,5.1,NaN,NaN,NaN,No,NaN,$25k-$50k,15,No,105%,Rust,NaN
4,S10004,NaN,Female,CompSci,NaN,0,5,2025-13-40,Yes,2029,Prefer not to say,41,No,NaN,Python,NaN

In [2]:
# 1. Load and inspect the data
print(df.shape)
display(df.head())
df.info()

(120, 16)

,student_id,age,gender,major,gpa,study_hours_per_week,satisfaction_1_5,survey_date,dorm_resident,expected_grad_year,income_range,commute_minutes,clubs_member,attendance_rate,favorite_language,comments
0,S10000,NaN,Male,Computer Science,NaN,NaN,2,2025-13-40,Yes,2027,>$100k,54,TRUE,105%,JavaScript,Love the course.
1,S10001,NaN,Male,CompSci,3.75,-3,NaN,NaN,Yes,NaN,NaN,NaN,1,NaN,Rust,Lectures are 🔥
2,S10002,23,Male,Data Science,NaN,20,5,2025-13-40,NaN,2027,$75k-$100k,NaN,NaN,64%,JavaScript,NaN
3,S10003,NaN,Female,History,5.1,NaN,NaN,NaN,No,NaN,$25k-$50k,15,No,105%,Rust,NaN
4,S10004,NaN,Female,CompSci,NaN,0,5,2025-13-40,Yes,2029,Prefer not to say,41,No,NaN,Python,NaN

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            120 non-null    str
 1   age                   87 non-null     str
 2   gender                97 non-null     str
 3   major                 110 non-null    str
 4   gpa                   76 non-null     str
 5   study_hours_per_week  78 non-null     str
 6   satisfaction_1_5      74 non-null     str
 7   survey_date           88 non-null     str
 8   dorm_resident         87 non-null     str
 9   expected_grad_year    87 non-null     str
 10  income_range          99 non-null     str
 11  commute_minutes       67 non-null     str
 12  clubs_member          95 non-null     str
 13  attendance_rate       41 non-null     str
 14  favorite_language     101 non-null    str
 15  comments              68 non-null     str
dtypes: str(16)
memory usage: 15.1 KB

In [3]:
# 2. Clean up string fields
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype("string").str.strip()
    df[col] = df[col].replace({"": pd.NA, "nan": pd.NA, "NaN": pd.NA})

df.head()

C:\Users\demii\AppData\Local\Temp\ipykernel_3980\197120342.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

,student_id,age,gender,major,gpa,study_hours_per_week,satisfaction_1_5,survey_date,dorm_resident,expected_grad_year,income_range,commute_minutes,clubs_member,attendance_rate,favorite_language,comments
0,S10000,<NA>,Male,Computer Science,<NA>,<NA>,2,2025-13-40,Yes,2027,>$100k,54,TRUE,105%,JavaScript,Love the course.
1,S10001,<NA>,Male,CompSci,3.75,-3,<NA>,<NA>,Yes,<NA>,<NA>,<NA>,1,<NA>,Rust,Lectures are 🔥
2,S10002,23,Male,Data Science,<NA>,20,5,2025-13-40,<NA>,2027,$75k-$100k,<NA>,<NA>,64%,JavaScript,<NA>
3,S10003,<NA>,Female,History,5.1,<NA>,<NA>,<NA>,No,<NA>,$25k-$50k,15,No,105%,Rust,<NA>
4,S10004,<NA>,Female,CompSci,<NA>,0,5,2025-13-40,Yes,2029,Prefer not to say,41,No,<NA>,Python,<NA>

In [4]:
# 3. Handle missing values
missing_before = df.isna().sum().sort_values(ascending=False)
missing_before

attendance_rate         79
commute_minutes         53
comments                52
satisfaction_1_5        46
gpa                     44
study_hours_per_week    42
dorm_resident           33
age                     33
expected_grad_year      33
survey_date             32
clubs_member            25
gender                  23
income_range            21
favorite_language       19
major                   10
student_id               0
dtype: int64

In [5]:
# 4. Standardize categorical data
gender_map = {
    "m": "Male", "male": "Male", "man": "Male",
    "f": "Female", "female": "Female", "woman": "Female",
    "other": "Other", "nonbinary": "Other", "non-binary": "Other",
}
df["gender"] = (
    df["gender"].astype("string").str.strip().str.lower().map(gender_map).fillna("Other")
)

major_map = {
    "compsci": "Computer Science",
    "computer science": "Computer Science",
    "cs": "Computer Science",
    "data science": "Data Science",
    "math": "Mathematics",
    "mathematics": "Mathematics",
}
df["major"] = df["major"].astype("string").str.strip().str.lower().map(major_map).fillna(df["major"])

df[["gender", "major"]].head()

   gender             major
0    Male  Computer Science
1    Male  Computer Science
2    Male      Data Science
3  Female           History
4  Female  Computer Science

In [6]:
# 5. Fix data types
def clean_number(series):
    return pd.to_numeric(series.astype("string").str.extract(r"(-?\d+(?:\.\d+)?)")[0], errors="coerce")

for col in ["age", "gpa", "study_hours_per_week", "satisfaction_1_5", "expected_grad_year", "commute_minutes"]:
    df[col] = clean_number(df[col])

df["survey_date"] = pd.to_datetime(df["survey_date"], errors="coerce")
df["attendance_rate"] = clean_number(df["attendance_rate"])

df.dtypes

C:\Users\demii\AppData\Local\Temp\ipykernel_3980\3338765751.py:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["survey_date"] = pd.to_datetime(df["survey_date"], errors="coerce")

student_id                      string
age                              Int64
gender                             str
major                              str
gpa                            Float64
study_hours_per_week           Float64
satisfaction_1_5                 Int64
survey_date             datetime64[us]
dorm_resident                   string
expected_grad_year               Int64
income_range                    string
commute_minutes                  Int64
clubs_member                    string
attendance_rate                  Int64
favorite_language               string
comments                        string
dtype: object

In [7]:
# 6. Validate and clean bounded numeric values
df.loc[(df["age"] < 16) | (df["age"] > 80), "age"] = np.nan
df.loc[(df["gpa"] < 0) | (df["gpa"] > 4), "gpa"] = np.nan
df.loc[(df["study_hours_per_week"] < 0) | (df["study_hours_per_week"] > 100), "study_hours_per_week"] = np.nan
df.loc[(df["satisfaction_1_5"] < 1) | (df["satisfaction_1_5"] > 5), "satisfaction_1_5"] = np.nan
df.loc[(df["attendance_rate"] < 0) | (df["attendance_rate"] > 100), "attendance_rate"] = np.nan

df.select_dtypes("number").describe()

,age,gpa,study_hours_per_week,satisfaction_1_5,expected_grad_year,commute_minutes,attendance_rate
count,80.0,54.0,52.0,58.0,87.0,67.0,16.0
mean,21.2375,3.75037,12.576923,2.87931,1591.241379,17.731343,82.75
std,2.312562,0.402801,8.589999,1.285241,831.111458,23.725438,12.720063
min,18.0,2.03,0.0,1.0,28.0,-5.0,62.0
25%,19.0,3.75,6.75,2.0,2026.0,-2.5,74.75
50%,21.0,3.75,12.5,3.0,2027.0,4.0,84.0
75%,23.0,4.0,20.0,4.0,2029.0,45.0,93.25
max,25.0,4.0,30.0,5.0,2030.0,75.0,99.0

In [8]:
# 7. Validate and clean emails if an email column exists
if "email" in df.columns:
    valid_email = df["email"].astype("string").str.match(r"^[^@\s]+@[^@\s]+\.[^@\s]+$", na=False)
    df.loc[~valid_email, "email"] = pd.NA
else:
    print("No email column exists in this survey file.")

No email column exists in this survey file.

In [9]:
# 8. Convert yes/no style fields to booleans
def to_bool(value):
    if pd.isna(value):
        return pd.NA
    text = str(value).strip().lower()
    if text in {"yes", "y", "true", "1"}:
        return True
    if text in {"no", "n", "false", "0"}:
        return False
    return pd.NA

for col in ["dorm_resident", "clubs_member"]:
    if col in df.columns:
        df[col] = df[col].apply(to_bool).astype("boolean")

df[["dorm_resident", "clubs_member"]].head()

   dorm_resident  clubs_member
0           True          True
1           True          True
2           <NA>          <NA>
3          False         False
4           True         False

In [10]:
# 9. Check for duplicates
duplicate_count = df.duplicated().sum()
print("Duplicate rows:", duplicate_count)
df = df.drop_duplicates().copy()

Duplicate rows: 0

In [11]:
# 10. Fill or flag remaining missing values
numeric_cols = df.select_dtypes(include="number").columns
for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

for col in df.select_dtypes(include="string").columns:
    df[col] = df[col].fillna("Unknown")

cleaned_missing = df.isna().sum().sort_values(ascending=False)
cleaned_missing

survey_date             59
dorm_resident           33
clubs_member            25
student_id               0
major                    0
gpa                      0
gender                   0
age                      0
satisfaction_1_5         0
study_hours_per_week     0
income_range             0
expected_grad_year       0
commute_minutes          0
attendance_rate          0
favorite_language        0
comments                 0
dtype: int64

In [12]:
# 11. Save the cleaned file
df.to_csv("survey_cleaned.csv", index=False)
df.head()

,student_id,age,gender,major,gpa,study_hours_per_week,satisfaction_1_5,survey_date,dorm_resident,expected_grad_year,income_range,commute_minutes,clubs_member,attendance_rate,favorite_language,comments
0,S10000,21,Male,Computer Science,3.75,12.5,2,NaT,True,2027,>$100k,54,True,84,JavaScript,Love the course.
1,S10001,21,Male,Computer Science,3.75,12.5,3,NaT,True,2027,Unknown,4,True,84,Rust,Lectures are 🔥
2,S10002,23,Male,Data Science,3.75,20.0,5,NaT,<NA>,2027,$75k-$100k,4,<NA>,64,JavaScript,Unknown
3,S10003,21,Female,History,3.75,12.5,3,NaT,False,2027,$25k-$50k,15,False,84,Rust,Unknown
4,S10004,21,Female,Computer Science,3.75,0.0,5,NaT,True,2029,Prefer not to say,41,False,84,Python,Unknown

## Cleaning Summary

The survey file was cleaned by trimming string columns, standardizing categories, coercing numeric fields, removing impossible values, converting yes/no fields into booleans, dropping duplicates, filling remaining missing values, and saving the result as `survey_cleaned.csv`. Some fields, such as invalid dates and out-of-range percentages, were treated as missing because keeping impossible values would distort later analysis.